# SPDX-FileCopyrightText: Alice Frosi <afrosi@redhat.com>
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "clevis-pin-trustee"
version = "0.1.0"
description = "Clevis PIN for URL-based encryption/decryption"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
base64 = "0.22.1"
clap = { version = "4.0", features = ["derive"] }
clevis-pin-trustee-lib = { path = "../lib" }
env_logger = "0.11.8"
hex = "0.4.3"
josekit = "0.10.3"
rand = "0.9.2"
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde.workspace = true
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tss-esapi = "7.6.0"

[dev-dependencies]
tempfile = "3.0"


